config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :matches, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :members, only: [:new, :create, :index, :edit, :update, :destroy]
  root to: "homes#top"
  get 'homes/top'
  get 'homes/team'
  get 'homes/inquiry'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
    has_one_attached :enemy_image

    def get_enemy_image
        unless enemy_image.attached?
            file_path = Rails.root.join('app/assets/images/image-no.jpg')
            enemy_image.attach(io:File.open(file_path), filename: 'default-image1.jpg', content_type: 'image/jpeg')
        end
        enemy_image
    end
end

app/models/member.rb
class Member < ApplicationRecord
    has_one_attached :profile_image

    def get_profile_image
        unless profile_image.attached?
            file_path = Rails.root.join('app/assets/images/no-image.jpg')
            profile_image.attach(io:File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
        end
        profile_image
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def after_sign_in_path_for(resource)
        matches_path
    end
    
    def after_sign_out_path_for(resource)
        homes_top_path
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def team
  end

  def inquiry
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @match = Match.new
  end

  def create
    @match = Match.new(match_params)
    @match.save
    redirect_to matches_path
  end

  def index
    @matches = Match.order(match_datetime: :desc).page(params[:page])
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    @match.update(match_params)
    redirect_to matches_path
  end

  def destroy
    @match = Match.find(params[:id])  # データ（レコード）を1件取得
    @match.destroy  # データ（レコード）を削除
    redirect_to matches_path  
  end

  private
  def match_params
    params.require(:match).permit(:title, :match_datetime, :enemy_team, :my_score, :enemy_score, :enemy_image)
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    @member.save
    redirect_to members_path
  end

  def index
    @members = Member.order(number: :asc)
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to members_path
  end

  def destroy
    @member = Member.find(params[:id])  # データ（レコード）を1件取得
    @member.destroy  # データ（レコード）を削除
    redirect_to members_path  
  end

  private
  def member_params
    params.require(:member).permit(:name, :furigana, :number, :birthday, :position, :profile_image)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/homes/inquiry.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">お問い合わせ</h3>
        </div>
    </div>
</div>

<div class="container">
    <div class="row mt-5">
        <div class="col-2">
        </div>
        <div class="col-4">
            <a href="https://www.instagram.com/saitama_2nd/?hl=ja">
                <%= image_tag("insta.jpg", class: 'img-fluid') %>
            </a>
        </div>
        <div class="col-6 inquiry-text" style="position: relative;">
            <div class="text-center" style="position: absolute; top: 50%; left: 25%; transform: translate(-50%, -50%);">
                InstagramのDMから<br>お問い合わせください<br>左の画像 click!
            </div>
        </div>
        <div class="col">
        </div>
    </div>
</div>

app/views/homes/team.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">チーム紹介</h3>
        </div>
    </div>
</div>

app/views/homes/top.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="top-visual">
            <%= image_tag("visual2.jpg", class: 'img-fluid') %>
        </div>
    </div>
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-sm-2">
        <div class="col-8 col-sm img_wrap ml-auto mr-auto mt-4 mt-sm-5" style="position: relative;">
            <%= link_to homes_team_path do %>
                <%= image_tag("team_img.jpg", class: 'img-fluid') %>
            <% end %>
        </div>
        <div class="col-8 col-sm img_wrap ml-auto mr-auto mt-4 mt-sm-5" style="position: relative;">
            <%= link_to members_path do %>
                <%= image_tag("member_img.jpg", class: 'img-fluid') %>
            <% end %>
        </div>
    </div>
    <div class="row mt-4 mt-md-5">
        <div class="col-8 col-sm-6 ml-auto mr-auto img_wrap" style="position: relative;">
            <%= link_to matches_path do %>
                <%= image_tag("result_img.jpg", class: 'img-fluid') %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homepage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="vh-100">
  <header>
      <nav class="navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand pl-3 pl-lg-5 pt-2" href="/homes/top">
            <%= image_tag("logo1.png", class: 'img-fluid') %>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item mr-4">
                <%= link_to "チーム紹介", homes_team_path, class: 'nav-link text-dark ' %>
              </li>
              <li class="nav-item mr-4" >
                <%= link_to '選手紹介', members_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item mr-4">
                <%= link_to '試合情報', matches_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "お問い合わせ", homes_inquiry_path, class: 'nav-link text-dark' %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer class="mt-5">
    <div class="container-fluid footer-box" style="height: 180px; background-color: gray;">
      <ul class="footer-list">
        <li class="footer-link">
          <%= link_to "トップページ", homes_top_path, class: 'nav-link text-white ' %>
        </li>
        <li class="footer-link">
          <%= link_to "チーム紹介", homes_team_path, class: 'nav-link text-white ' %>
        </li>
        <li class="footer-link">
          <%= link_to '選手紹介', members_path, class: 'nav-link text-white' %>
        </li>
        <li class="footer-link">
          <%= link_to '試合情報', matches_path, class: 'nav-link text-white' %>
        </li>
        <li class="footer-link">
          <%= link_to "お問い合わせ", homes_inquiry_path, class: 'nav-link text-white' %>
        </li>
        <a class="footer-logo" href="/homes/top">
          <%= image_tag("logo2.png", class: 'img-fluid') %>
        </a>
      </ul>
    </div>
  </footer>
  </body>
</html>

app/views/matches/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">メンバー編集・削除</h3>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <%= form_with model: @match, url:match_path(@match.id), method: :patch do |f| %>
            <div class="form-title">
                <%= f.label :title , "試合名"%>
            </div>
            <div class="form-name">
                <%= f.text_field :title %> 
            </div>

            <div class="form-title">
                <%= f.label :match_datetime, "試合日時" %>
            </div>
            <div class="form-day">
                <%= f.datetime_field :match_datetime %>  
            </div>

            <div class="form-title">
                <%= f.label :enemy_team, "敵チーム名"%>
            </div>
            <div class="form-name">
                <%= f.text_field :enemy_team %> 
            </div>

            <div class="form-title">
                <%= f.label :my_score, "Saitama 2nd. 得点数"%>
            </div>
            <div class="form-number">
                <%= f.number_field :my_score %>
            </div>

            <div class="form-title">
                <%= f.label :enemy_score, "敵チーム 得点数"%>
            </div>
            <div class="form-number">
                <%= f.number_field :enemy_score %>
            </div>

            <div class="form-title">
                <%= f.label :enemy_image, "敵エンブレム"%>
            </div>
            <div class="form-image">
                <%= f.file_field :enemy_image, accept: "image/*" %>
            </div>
            
            <%= f.submit '変更' %>
        <% end %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="destroy">
            <%= link_to "削除", match_path(@match.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
        </div>
    </div>
</div>

app/views/matches/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">試合情報</h3>
        </div>
    </div>
</div>
<div class="container schedule-table rounded pr-0 pl-0 mt-3 mt-md-4">
    <p class="schedule-title rounded-top p-2 pl-3 mb-4"><strong>日程表</strong></p>
    <% @matches.each do |match| %>
        <div class="row mr-3 mr-md-4 mr-lg-5 ml-3 ml-md-4 ml-lg-5">
            <div class="col-12 schedule-match pt-2 pb-2 mb-4">
                <div class="schedule-match-top text-center">
                    <% if user_signed_in? %>
                        <span> id = <%= match.id %></span>
                    <% end %>
                    <span class="schedule-match-title">　<%= match.title %></span><br>
                    <% if match.match_datetime.present? %>
                        <span class="schedule-match-datetime">　<%= match.match_datetime.strftime('%Y 年 %m 月 %d 日　%H : %M ～') %></span>
                    <% else %>
                        <span class="schedule-match-datetime">　???? 年 ?? 月 ?? 日　?? : ?? ～</span>
                    <% end %>
                </div>
                <div class="schedule-match-bottom mt-2">
                    <div class="row row-cols-3">
                        <div class="col-4 col-sm-5 align-self-start text-center text-truncate">
                            <span class="schedule-team"><%= image_tag "logo.png", size: "50x50" %><br>Saitama 2nd.</span>
                        </div>
                        <div class="col-4 col-sm-2 align-self-center text-center">
                            <% if match.my_score.present? %>
                                <span class="schedule-score"><%= match.my_score %> － <%= match.enemy_score %></span>
                            <% else %>
                                <span class="schedule-score">？ － ？</span>
                            <% end %>
                        </div>
                        <div class="col-4 col-sm-5 align-self-end text-center text-truncate">
                            <span class="schedule-team"><%= image_tag match.get_enemy_image, size: "50x50" %><br><%= match.enemy_team %></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
    <div class="row justify-content-center">
        <div class = "col-auto">
            <%= paginate @matches %>
        </div>
    </div>
</div>

app/views/matches/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">試合情報追加</h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <%= form_with model: @match do |f| %>
            <div class="form-title">
                <%= f.label :title , "試合名"%>
            </div>
            <div class="form-name">
                <%= f.text_field :title %> 
            </div>

            <div class="form-title">
                <%= f.label :match_datetime, "試合日時" %>
            </div>
            <div class="form-datetime">
                <%= f.datetime_field :match_datetime %>  
            </div>

            <div class="form-title">
                <%= f.label :enemy_team, "敵チーム名"%>
            </div>
            <div class="form-name">
                <%= f.text_field :enemy_team %> 
            </div>

            <div class="form-title">
                <%= f.label :my_score, "Saitama 2nd. 得点数"%>
            </div>
            <div class="form-number">
                <%= f.number_field :my_score %>
            </div>

            <div class="form-title">
                <%= f.label :enemy_score, "敵チーム 得点数"%>
            </div>
            <div class="form-number">
                <%= f.number_field :enemy_score %>
            </div>

            <div class="form-title">
                <%= f.label :enemy_image, "敵エンブレム"%>
            </div>
            <div class="form-image">
                <%= f.file_field :enemy_image, accept: "image/*" %>
            </div>

            <%= f.submit '追加' %>
        <% end %>
    </div>
</div>

app/views/members/edit.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">メンバー編集・削除</h3>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <%= form_with model: @member, url:member_path(@member.id), method: :patch do |f| %>
            <div class="form-title">
                <%= f.label :name , "名前"%>
            </div>
            <div class="form-name">
                <%= f.text_field :name %> 
            </div>

            <div class="form-title">
                <%= f.label :furigana , "名前(ふりがな)"%>
            </div>
            <div class="form-furigana">
                <%= f.text_field :furigana %> 
            </div>

            <div class="form-title">
                <%= f.label :number, "背番号" %>
            </div>
            <div class="form-number">
                <%= f.number_field :number %> 
            </div>

            <div class="form-title">
                <%= f.label :birthday, "生年月日"%>
            </div>
            <div class="form-day">
                <%= f.date_select :birthday, use_two_digit_numbers: true, start_year: 1995  %> 
            </div>

            <div class="form-title">
                <%= f.label :position, "ポジション"%>
            </div>
            <div class="form-position">
                <%= f.text_field :position %> 
            </div>

            <div class="form-title">
                <%= f.label :profile_image, "顔写真"%>
            </div>
            <div class="form-image">
                <%= f.file_field :profile_image, accept: "image/*" %>
            </div>
            
            <%= f.submit '変更' %>
        <% end %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="destroy">
            <%= link_to "削除", member_path(@member.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
        </div>
    </div>
</div>

app/views/members/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">選手紹介</h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 mt-3">
        <% @members.each do |member| %>
            <div class="col text-center mt-3">
                <%= image_tag member.get_profile_image, class: "img-fluid" %><br>
                <span class="member-furigana"><%= member.furigana %></span><br>
                <% if user_signed_in? %>
                    <span> id = <%= member.id %></span>
                <% end %>
                <span class="member-name"><%= member.name %></span><br>
                <span class="member-number">背番号：<strong class="strong-number"><%= member.number %></strong></span><br>
                <span class="member-position">ポジション：<%= member.position %></span><br>
                <span class="member-birthday"><%= member.birthday.strftime('%Y年%m月%d日') %></span>
            </div>
        <% end %>
    </div>
</div>

app/views/members/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="main-visual">
            <h1 class="main-title">メンバー追加</h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <%= form_with model: @member do |f| %>
            <div class="form-title">
                <%= f.label :name , "名前"%>
            </div>
            <div class="form-name">
                <%= f.text_field :name %> 
            </div>

            <div class="form-title">
                <%= f.label :furigana , "名前(ふりがな)"%>
            </div>
            <div class="form-furigana">
                <%= f.text_field :furigana %> 
            </div>

            <div class="form-title">
                <%= f.label :number, "背番号" %>
            </div>
            <div class="form-number">
                <%= f.number_field :number %> 
            </div>

            <div class="form-title">
                <%= f.label :birthday, "生年月日"%>
            </div>
            <div class="form-day">
                <%= f.date_select :birthday, use_two_digit_numbers: true, start_year: 1995 %> 
            </div>

            <div class="form-title">
                <%= f.label :position, "ポジション"%>
            </div>
            <div class="form-position">
                <%= f.text_field :position %> 
            </div>

            <div class="form-title">
                <%= f.label :profile_image, "顔写真"%>
            </div>
            <div class="form-image">
                <%= f.file_field :profile_image, accept: "image/*" %>
            </div>
            
            <%= f.submit '追加' %>
        <% end %>
    </div>
</div>